#%RAML 1.0
---
title: Congratulations API
baseUri: http://congratulationsp.ru/api
version: v1
mediaType: application/json

description: |
    This is API for creating Congratulatory cards    
    Developer: [platon-p](https://github.com/platon-p)

types:
    preset:
        type: object
        properties:
            ID: number
            CreatedAt: string
            UpdatedAt: string
            DeletedAt?: string
            name: string
            paperSize: string
            text: string
            greeting: string
            textX: number
            textY: number
            greetingY: number
            image: string
        example: |
                {
                    "ID": 2,
                    "CreatedAt": "2022-05-06T13:37:37.620969+03:00",
                    "UpdatedAt": "2022-05-08T17:21:43.488331+03:00",
                    "DeletedAt": null,
                    "name": "9 мая",
                    "paperSize": "A4",
                    "text": "asdsadasjkdnasjknasdjaskdnjk",
                    "greeting": "Здравствуйте, {}!",
                    "textX": 30,
                    "textY": 60,
                    "greetingY": 30,
                    "image": "backgrounds/gramota.jpg"
                }

    presets:
        type: preset[]

    error:
        type: string
        madiaType: text/plain
        properties:
            error: string

    idError:
        type: error
        example: |
            error: Bad id


/preset:
    displayName: Preset
    get:
        description: Returns information about preset by given ID
        queryParameters:
            id:
                type: number
        responses:
            200:
                body:
                    type: preset
            400:
                body:
                    text/plain:
                        type: idError



/presets:
    displayName: List of Presets
    get:
        description: Get list of available presets
        responses:
            200:
                body:
                    type: presets
                    example: |
                        [
                            {
                                "ID": 1,
                                "CreatedAt": "2022-05-06T13:37:37.620969+03:00",
                                "UpdatedAt": "2022-05-06T13:37:37.620969+03:00",
                                "DeletedAt": null,
                                "name": "Благодарственное письмо",
                                "paperSize": "A4",
                                "text": "Ea tempor in pariatur ea enim nulla eiusmod. Nulla fugiat consequat occaecat est id consectetur Lorem voluptate ut amet sunt tempor. Nulla fugiat consequat occaecat est id consectetur Lorem voluptate ut amet sunt tempor.",
                                "greeting": "[Уважаемый][Уважаемая] {}!",
                                "textX": 30,
                                "textY": 60,
                                "greetingY": 30,
                                "image": "backgrounds/gramota.jpg"
                            },
                            {
                                "ID": 2,
                                "CreatedAt": "2022-05-06T13:37:37.620969+03:00",
                                "UpdatedAt": "2022-05-08T17:21:43.488331+03:00",
                                "DeletedAt": null,
                                "name": "9 мая",
                                "paperSize": "A4",
                                "text": "asdsadasjkdnasjknasdjaskdnjk",
                                "greeting": "Здравствуйте, {}!",
                                "textX": 30,
                                "textY": 60,
                                "greetingY": 30,
                                "image": "backgrounds/gramota.jpg"
                            },
                            {
                                "ID": 3,
                                "CreatedAt": "2022-05-08T16:32:08.2887+03:00",
                                "UpdatedAt": "2022-05-08T16:32:08.2887+03:00",
                                "DeletedAt": null,
                                "name": "9 мая",
                                "paperSize": "A4",
                                "text": "asdsadasjkdnasjknasdjaskdnjk",
                                "greeting": "Здравствуйте, {}!",
                                "textX": 30,
                                "textY": 60,
                                "greetingY": 30,
                                "image": "backgrounds/gramota/jpg"
                            }
                        ]

/pdf:
    displayName: Generate PDF
    get:
        description: Generate PDF by id of preset, gender and name
        queryParameters:
            id: number
        responses:
            200:
                body:
                    application/pdf:
            400:
                body:
                    text/plain:
                        type: idError