#%RAML 1.0
---
title: Congratulations API
baseUri: http://congratulationsp.ru/api
version: v1


types:
    preset: {
        "type": object,
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "http://jsonschema.net",
        "required": true,
        "properties": {
            "Name": {"type": "string"},
            "PaperSize": {"type": "string"},
            "Text": {"type": "string"},
            "Greeting": {"type": "string"},
            "TextX": {"type": "number"},
            "TextY": {"type": "number"},
            "GreetingY": {"type": "number"},
            "Image": {"type": "string"}
        }
    }

    presets:
        type: array

/preset:
    get:
        queryParameters:
            id:
                type: number
                required: true
        responses:
            200:
                body:
                    type: preset
                    application/json:
                        example: |
                            {
                                {
                                  "ID": 1,
                                  "CreatedAt": "2022-05-06T13:37:37.620969+03:00",
                                  "UpdatedAt": "2022-05-06T13:37:37.620969+03:00",
                                  "DeletedAt": null,
                                  "Name": "Благодарственное письмо",
                                  "PaperSize": "A4",
                                  "Text": "Ea tempor in pariatur ea enim nulla eiusmod. Nulla fugiat consequat occaecat est id consectetur Lorem voluptate ut amet sunt tempor. Nulla fugiat consequat occaecat est id consectetur Lorem voluptate ut amet sunt tempor.",
                                  "Greeting": "[Уважаемый][Уважаемая] {}!",
                                  "TextX": 30,
                                  "TextY": 60,
                                  "GreetingY": 30,
                                  "Image": "backgrounds/gramota.jpg"
                                }
                            }

/presets:
    get:
        responses:
            200:
              body:
              type: presets
                application/json:
                  example: |
                    [
                      {
                        "ID": 1,
                        "CreatedAt": "2022-05-06T13:37:37.620969+03:00",
                        "UpdatedAt": "2022-05-06T13:37:37.620969+03:00",
                        "DeletedAt": null,
                        "Name": "Благодарственное письмо",
                        "PaperSize": "A4",
                        "Text": "Ea tempor in pariatur ea enim nulla eiusmod. Nulla fugiat consequat occaecat est id consectetur Lorem voluptate ut amet sunt tempor. Nulla fugiat consequat occaecat est id consectetur Lorem voluptate ut amet sunt tempor.",
                        "Greeting": "[Уважаемый][Уважаемая] {}!",
                        "TextX": 30,
                        "TextY": 60,
                        "GreetingY": 30,
                        "Image": "backgrounds/gramota.jpg"
                      },
                      {
                        "ID": 2,
                        "CreatedAt": "2022-05-06T13:37:37.620969+03:00",
                        "UpdatedAt": "2022-05-08T17:21:43.488331+03:00",
                        "DeletedAt": null,
                        "Name": "9 мая",
                        "PaperSize": "A4",
                        "Text": "asdsadasjkdnasjknasdjaskdnjk",
                        "Greeting": "Здравствуйте, {}!",
                        "TextX": 30,
                        "TextY": 60,
                        "GreetingY": 30,
                        "Image": "backgrounds/gramota.jpg"
                      },
                      {
                        "ID": 3,
                        "CreatedAt": "2022-05-08T16:32:08.2887+03:00",
                        "UpdatedAt": "2022-05-12T10:16:34.192872+03:00",
                        "DeletedAt": null,
                        "Name": "День рождения",
                        "PaperSize": "A4",
                        "Text": "asdsadasjkdnasjknasdjaskdnjk",
                        "Greeting": "Здравствуйте, {}!",
                        "TextX": 30,
                        "TextY": 60,
                        "GreetingY": 30,
                        "Image": "backgrounds/gramota.jpg"
                      }
                    ]